apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: per-jenkins
  namespace: argocd
project: default
destination:
  server: 'https://kubernetes.default.svc'
  namespace: student-16
syncPolicy:
  automated:
    prune: true
    selfHeal: true
sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 12.4.0
    helm:
      valueFiles:
        - $values/jenkins/values.yaml
    chart: jenkins
  - repoURL: 'https://github.com/belegaps/argocd-katas-training'
    targetRevision: main
    ref: values
